// Code generated by protoc-gen-go.
// source: message.proto
// DO NOT EDIT!

/*
Package engine is a generated protocol buffer package.

It is generated from these files:
	message.proto

It has these top-level messages:
	Action
	ServerUpdate
*/
package engine

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// actions taken by a client
type Action struct {
	Desc string `protobuf:"bytes,1,opt,name=desc" json:"desc,omitempty"`
}

func (m *Action) Reset()                    { *m = Action{} }
func (m *Action) String() string            { return proto.CompactTextString(m) }
func (*Action) ProtoMessage()               {}
func (*Action) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Action) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

type ServerUpdate struct {
	Desc string `protobuf:"bytes,1,opt,name=desc" json:"desc,omitempty"`
}

func (m *ServerUpdate) Reset()                    { *m = ServerUpdate{} }
func (m *ServerUpdate) String() string            { return proto.CompactTextString(m) }
func (*ServerUpdate) ProtoMessage()               {}
func (*ServerUpdate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ServerUpdate) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func init() {
	proto.RegisterType((*Action)(nil), "engine.Action")
	proto.RegisterType((*ServerUpdate)(nil), "engine.ServerUpdate")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for MessageStream service

type MessageStreamClient interface {
	UpdateStream(ctx context.Context, opts ...grpc.CallOption) (MessageStream_UpdateStreamClient, error)
}

type messageStreamClient struct {
	cc *grpc.ClientConn
}

func NewMessageStreamClient(cc *grpc.ClientConn) MessageStreamClient {
	return &messageStreamClient{cc}
}

func (c *messageStreamClient) UpdateStream(ctx context.Context, opts ...grpc.CallOption) (MessageStream_UpdateStreamClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_MessageStream_serviceDesc.Streams[0], c.cc, "/engine.MessageStream/UpdateStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &messageStreamUpdateStreamClient{stream}
	return x, nil
}

type MessageStream_UpdateStreamClient interface {
	Send(*Action) error
	Recv() (*ServerUpdate, error)
	grpc.ClientStream
}

type messageStreamUpdateStreamClient struct {
	grpc.ClientStream
}

func (x *messageStreamUpdateStreamClient) Send(m *Action) error {
	return x.ClientStream.SendMsg(m)
}

func (x *messageStreamUpdateStreamClient) Recv() (*ServerUpdate, error) {
	m := new(ServerUpdate)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for MessageStream service

type MessageStreamServer interface {
	UpdateStream(MessageStream_UpdateStreamServer) error
}

func RegisterMessageStreamServer(s *grpc.Server, srv MessageStreamServer) {
	s.RegisterService(&_MessageStream_serviceDesc, srv)
}

func _MessageStream_UpdateStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MessageStreamServer).UpdateStream(&messageStreamUpdateStreamServer{stream})
}

type MessageStream_UpdateStreamServer interface {
	Send(*ServerUpdate) error
	Recv() (*Action, error)
	grpc.ServerStream
}

type messageStreamUpdateStreamServer struct {
	grpc.ServerStream
}

func (x *messageStreamUpdateStreamServer) Send(m *ServerUpdate) error {
	return x.ServerStream.SendMsg(m)
}

func (x *messageStreamUpdateStreamServer) Recv() (*Action, error) {
	m := new(Action)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _MessageStream_serviceDesc = grpc.ServiceDesc{
	ServiceName: "engine.MessageStream",
	HandlerType: (*MessageStreamServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UpdateStream",
			Handler:       _MessageStream_UpdateStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "message.proto",
}

func init() { proto.RegisterFile("message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 137 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4b, 0xcd, 0x4b, 0xcf, 0xcc,
	0x4b, 0x55, 0x92, 0xe1, 0x62, 0x73, 0x4c, 0x2e, 0xc9, 0xcc, 0xcf, 0x13, 0x12, 0xe2, 0x62, 0x49,
	0x49, 0x2d, 0x4e, 0x96, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x95, 0x94, 0xb8, 0x78,
	0x82, 0x53, 0x8b, 0xca, 0x52, 0x8b, 0x42, 0x0b, 0x52, 0x12, 0x4b, 0x52, 0xb1, 0xa9, 0x31, 0xf2,
	0xe6, 0xe2, 0xf5, 0x85, 0x18, 0x1d, 0x5c, 0x52, 0x94, 0x9a, 0x98, 0x2b, 0x64, 0xc5, 0xc5, 0x03,
	0x51, 0x0e, 0xe5, 0xf3, 0xe9, 0x41, 0xec, 0xd2, 0x83, 0x58, 0x24, 0x25, 0x02, 0xe3, 0x23, 0x1b,
	0xad, 0xc4, 0xa0, 0xc1, 0x68, 0xc0, 0x98, 0xc4, 0x06, 0x76, 0x9d, 0x31, 0x20, 0x00, 0x00, 0xff,
	0xff, 0x0f, 0x2b, 0x40, 0xc7, 0xae, 0x00, 0x00, 0x00,
}
